#!/bin/bash
# SRCDS Server
# FastDL Creator
# Author : Robin Labadie aka UltimateByte
# Website : http://www.lrob.fr for http://www.mesnie.org
# Version : 1.0

# README
# This script is intended to work only for Valve SRCDS (Source) servers using Daniel Gibbs Linux Game Servers Management script
# It's been tested for Debian 8 but other debian and distros should also work
# After running this, you have to setup an HTTP server pointing to the fastdl folder that will be created
# Of course, you will also have to change your server configuration's sv_downloadurl
# If my work helped you, please consider making a donation on www.mesnie.org


# CONFIGURATION
# The SRCDS name of the game
gamename="garrysmod"


# SCRIPT 
# Directories
rootdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
serverdir="${rootdir}/serverfiles/${gamename}"
fastdl="${rootdir}/fastdl"
addons="${serverdir}/addons"

# Welcome message
echo "Welcome to FastDL folder Creator"
echo "Checking configuration..."
sleep 2

# Check if lgsm directories seems to exists and be standard, if not, exit
if [ -d "$serverdir" ]; then
	echo "Good, your lgsm installation and script configuration are fine"
else 
	echo "Sorry, your lgsm installation was not found"
	echo "Please make sure to read the README at the beginning of the script"
	sleep 2
	exit
fi 


# User confirmation for starting process
while true; do
	read -p "Do you wish to continue? [y/N]" yn
	case $yn in
	[Yy]* ) break;;
	[Nn]* ) exit;;
	* ) echo "Please answer yes or no.";;
	esac
done

# Check if bzip2 is installed
bzip2="dpkg-query -l | grep bzip2 | wc -l"

# Warning if bzip2 is not installed
if [ "$bzip2" = 0 ]; then
	echo "WARNING bzip2 is not installed"
	echo "You can still continue but loading time won't be as best as possible for your players"
	while true; do
		read -p "Do you wish to continue? [y/N]" yn
		case $yn in
		[Yy]* ) break;;
		[Nn]* ) exit;;
		* ) echo "Please answer yes or no.";;
		esac
	done
fi

# Create FastDL folder if it doesn't exit
if [ ! -d "$fastdl" ]; then
	mkdir -v "${fastdl}"
fi


# Copy all needed files for fastDL
echo "Gathering all needed FastDL files..."
sleep 2

# Map Files
echo "Copying map files"
sleep 1
find "${serverdir}" -name '*.bsp' | cpio -pdmu "${fastdl}"

# Materials
echo "Copying Materials"
sleep 1
find "${serverdir}" -name '*.vtf' | cpio -pdmu "${fastdl}"
find "${serverdir}" -name '*.vmt' | cpio -pdmu "${fastdl}"

# Models
echo "Copying Models"
sleep 1
find "${serverdir}" -name '*.vtx' | cpio -pdmu "${fastdl}"
find "${serverdir}" -name '*.vvd' | cpio -pdmu "${fastdl}"
find "${serverdir}" -name '*.mdl' | cpio -pdmu "${fastdl}"
find "${serverdir}" -name '*.phy' | cpio -pdmu "${fastdl}"
find "${serverdir}" -name '*.vvd' | cpio -pdmu "${fastdl}"

# Particles
echo "Copying Paricles"
sleep 1
find "${serverdir}" -name '*.pcf' | cpio -pdmu "${fastdl}"

# Sounds
echo "Copying Sounds"
sleep 1
find "${serverdir}" -name '*.wav' | cpio -pdmu "${fastdl}"
find "${serverdir}" -name '*.mp3' | cpio -pdmu "${fastdl}"

# Resources (mostly fonts)
echo "Copying Resources (mostly fonts)"
sleep 1
find "${serverdir}" -name '*.otf' | cpio -pdmu "${fastdl}"
find "${serverdir}" -name '*.ttf' | cpio -pdmu "${fastdl}"

echo "Done"
sleep 2

# Correct addons folder structure
echo "Moving addons' FastDL files to their correct folder"
sleep 2
mv -f "${fastdl}/addons/*/*" "${fastdl}"
rm -R "${fastdl}/addons"

# Correct content that may be into a lua folder by mistake like darkrpmodification
echo "Correcting possible resources in lua folders like for darkrpmodification"
sleep 1
cp -Rf "${fastdl}/lua/*" "${fastdl}"

# bzip2 compression
# End if bzip2 not installed
if [ "$bzip2" = 0 ]; then
	echo "Done, now please configure your HTTP server to target the fastdl folder that was created"
	echo "Don't forget to change your sv_downloadurl in server configuration"
	sleep 2
	exit
fi

# Files Compression with bzip2
# User confirmation for bzip2

echo "FastDL will now compress files using bzip2"
while true; do
	read -p "Do you wish to continue? [y/N]" yn
	case $yn in
	[Yy]* ) break;;
	[Nn]* ) exit;;
	* ) echo "Please answer yes or no.";;
	esac
done

# bzip2 all files that are not already compressed
find "$fastdl" -not -name \*.bz2 -exec bzip2 \{\} \;
echo "bzip2 compression done"
sleep 1
echo "Now please configure your HTTP server to target the fastdl folder that was created"
echo "Don't forget to change your sv_downloadurl in server configuration"
sleep 2
exit
