#!/bin/bash
# SRCDS Server
# FastDL Creator
# Author : Robin Labadie
# Website : http://www.lrob.fr for http://www.mesnie.org
# Version : 1.0

# README
# This script is intended to work only for Valve SRCDS (Source) servers using Daniel Gibbs Linux Game Servers Management script
# It's been tested for Debian 8 but other debian and distros should also work
# After running this, you have to setup an HTTP server pointing to the fastdl folder that will be created
# Of course, you will also have to change your server configuration
# If my work helped you, please consider making a donation on www.mesnie.org


# CONFIGURATION

# The SRCDS name of the game
gamename="garrysmod"

# Enable/disable b2zip compression (1 enabled, 0 disabled)
b2zip="1"



# SCRIPT 

# Directories
rootdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
serverdir="${rootdir}/serverfiles/${gamename}"
fastdl="${rootdir}/fastdl"
addons="${serverdir}/addons"

# Welcome message
echo "You're up to create a fastdl folder where the script is located"
echo "Checking configuration..."
sleep 2



# Check if lgsm directories seems to exists and be standard
if [ -d $serverdir ]; then
	echo "Your lgsm installation and script configuration seems fine"
else 
	echo "Your lgsm installation was not found"
	echo "Please make sure to read the README at the beginning of the script"
	echo "Script will now exit..."
	sleep 2
	exit
fi 


echo -e "Continue ? y or n"



# Coding note : find /folder/subfolder -not -name \*.bz2 -exec bzip2 \{\} \;

# Map Files
echo Copying map files
find ${serverdir} -name '*.bsp' | cpio -pdm ${fastdl}

# 
find ${serverdir} -name '*.otf' | cpio -pdm ${fastdl}

find ${serverdir} -name '*.ttf' | cpio -pdm ${fastdl}
find ${serverdir} -name '*.vtf' | cpio -pdm ${fastdl}


find ${serverdir} -name '*.vmt' | cpio -pdm ${fastdl}
find ${serverdir} -name '*.vvd' | cpio -pdm ${fastdl}
find ${serverdir} -name '*.vtx' | cpio -pdm ${fastdl}
find ${serverdir} -name '*.phy' | cpio -pdm ${fastdl}
find ${serverdir} -name '*.mdl' | cpio -pdm ${fastdl}

# Particles
# .pcf
